### ISSUE TITLE
Missing information when importing a filegeodatabase

### ISSUE THREAD

**Issue by sindile** [cartologic/fgdb2postgis#1]
I am trying to import a file geodatabase based on http://solutions.arcgis.com/parks-gardens/help/parks-and-gardens-information-model/
This is provided as a xml file which I import into an empty file geodatabase. The xml file is a schema with no data.
I created a folder "pagim" with the following files - pagim.gdb and pagim.yaml (should the yaml file be pagim.gdb.yaml or pagim.yaml?)

In my yaml file I have the following (I only defined a single schema pagim):
Schemas:
  - pagim
FeatureDatasets:
  pagim:
    - Basemap
    - Boundary
    - Electric
    - Gas
    - Hydrography
    - Irrigation
    - Pedology
    - Sewer
    - StormWater
    - Telecommunication
    - Topography
    - Vegetation
    - VisitorAmenity
    - Water
    - Basemap
Tables:
  pagim:
    - AsssetMaintenance
    - Dedication
    - Enclosure
    - Institution
    - PlantAccession
    - PlantLabel
    - PlantMaintenance
    - ProductInformation
    - TreeBenefit
    - TreeHazardHealth
    - WaterSample
The script is able to run with the following exceptions
1. If a domain name has a dash (-) like my-domain, the script will fail complaining about invalid character (renaming the domain solves this)
2. 
Applying sql scripts ...
Traceback (most recent call last):
  File "c:\python27\arcgis10.3\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\arcgis10.3\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\ArcGIS10.3\Scripts\fgdb2postgis.exe\__main__.py", line 9, in <module>
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\__main__.py", line 63, in main
    postgis.apply_sql(filegdb)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 95, in apply_sql
    self.execute_sql(sql_file)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 104, in execute_sql
    cursor.execute(code)
psycopg2.ProgrammingError: column "GLOBALID" of relation "IrrigationLine" does not exist
LINE 2: INSERT INTO "IrrigationLine" ("GLOBALID")

I am not sure whether the above (2) error is because of the empty table.

3. Whilst I have a yaml file with a schema defined is seems to be ignored as all the table are placed in the public schema - perhaps I have not defined my yaml file correctly.

4. The tables for relationship classes are not imported

**Comment by sindile** [comment]
The yaml file should be named filename.gdb.yaml - confirmed as the schema defined was created in Postgis database.
The tables were not copied to the schema though but rather to public
Here is the output of my latest iteration of the import:
G:\landscape_gis\ParksAndGardensInformationModel2.0.0\converttopostgis_3>fgdb2postgis.exe -f pagimdb.gdb -p pagimdb --host=localhost --port=5432 --user=postgres --password=jama135

FileGDB Info:
 Workspace: G:\landscape_gis\ParksAndGardensInformationModel2.0.0\converttopostgis_3\pagimdb.gdb
 Sqlfolder: G:\landscape_gis\ParksAndGardensInformationModel2.0.0\converttopostgis_3\pagimdb.gdb.sql
 Yamlfile: G:\landscape_gis\ParksAndGardensInformationModel2.0.0\converttopostgis_3\pagimdb.gdb.yaml

Setting arcpy environment ...

Initializing sql files ...

Processing domains ...
 HydrographicFlowClass_lut
 WaterConsumption_lut
 YesNo_lut
 WasteContainerConstructionType_lut
 PlantStatus_lut
 AccessType_lut
 WaterSource_lut
 NonvascularSparseVascularRockSubclass_lut
 PavementConstructionType_lut
 InsectGenus_lut
 InsectOrder_lut
 iTreeStatusCode_lut
 InsectSpecies_lut
 PathogenName_lut
 TrafficCalmingConstructionType_lut
 SurveyMethod_lut
 BarrierFunction_lut
 HydrographicShoreClass_lut
 PlantingSize_lut
 FailurePartSize_lut
 InfraspecificRank_lut
 LifeCycleStatus_lut
 BarrierSecurityType_lut
 SunsetCode_lut
 1 Min value
 24 Max value
 HydrographicMonitoringType_lut
 UnpavedSurfaceConstructionType_lut
 PRI_lut
 PlantLabelSize_lut
 SemiDesertSubclass_lut
 ForestWoodlandSubclass_lut
 WireType_lut
 Lime_lut
 MonitoringPointType_lut
 FailurePotential_lut
 ContainerSize_lut
 WaterReservoirConstructionType_lut
 BollardConstructionType_lut
 ReferenceGridName_lut
 ParkingFeeType_lut
 USDAZone_lut
 AssetCondition_lut
 HydrographicStructureType_lut
 BoxSize_lut
 PlantingAreaName_lut
 Pattern_lut
 Conks_lut
 Priority_lut
 AcquiredMaterialType_lut
 FurnitureConstructionType_lut
 PoleConstructionType_lut
 TargetRating_lut
 LivingCollectionName_lut
 WorkOrderStatus_lut
 ShurblandGrasslandSubclass_lut
 iTreePercentage_lut
 -1 Min value
 100 Max value
 InsectFamily_lut
 WaterSourceType_lut
 AnnotationStatus_lut
 PolarHighMontaneSubclass_lut
 IrrigationHeadType_lut
 PipeMaterial_lut
 Severity_lut
 AquaticSubclass_lut
 SoilTestLevel_lut
 TrafficSignSubtypeWarning_lut
 CrownLightExposure_lut
 -1 Min value
 5 Max value
 InsectCommonName_lut
 iTreeDBH_lut
 -1 Min value
 200 Max value
 HazardRating_lut
 PlantMaintenanceType_lut
 PlantingBedName_lut
 PavementMarkingColor_lut
 ConditionRating_lut
 WaterUse_lut
 PlantCondition_lut
 RotationAngle_lut
 0 Min value
 360 Max value
 BarrierConstructionType_lut
 AssetMaintenanceType_lut
 GeologicAgePeriod_lut
 Frequency_lut
 SoilTexture_lut
 iTreeLandUseCode_lut
 CurbConstructionType_lut
 iTreeSiteCode_lut
 TrafficSignSubtypeGuide_lut
 PlantHabit_lut
 LandscapeStructureConstructionType_lut
 iTreeWidth_lut
 -1 Min value
 300 Max value
 iTreeSpeciesCode_lut
 GeologicAgeEpoch_lut
 AHSHeatCode_lut
 1 Min value
 12 Max value
 TrafficSignSubtypeRegulatory_lut
 Conflict_lut
 GeologicAgeEra_lut
 iTreeHeight_lut
 -1 Min value
 450 Max value
 VerticalAlignment_lut
 SectionName_lut
 HydrographicOtherPointType_lut
 HydrographicWaterType_lut
 HorizontalAlignment_lut
 BooleanSymbolValue_lut
 TrafficSignSupportType_lut
 ParkingType_lut
 TrafficLoad_lut
 iTreeDBHHeight_lut
 -1 Min value
 6 Max value
 Status_lut

Processing subtypes ...
 AsssetMaintenance_MAINTENANCERECORDTYPE_lut
 PlantMaintenance_MAINTENANCERECORDTYPE_lut

Processing relations ...
 IrrigationLineHasAssetMaintenances
 IrrigationHeadHasProductInformation
 PavementSegmentHasAssetMaintenances
 StormWaterLineHasAssetMaintenances
 StructureHasDedications
 TelecommunicationLineHasAssetMaintenances
 UtilityVaultHasProductInformation
 StructureHasEnclosures
 TrafficSignHasAssetMaintenances
 WaterPointHasAssetMaintenances
 LandscapeStructureHasAssetMaintenances
 PlantAccessionHasPlantCenters
 LandscapeStructureHasDedications
 UnpavedSurfaceHasAssetMaintenances
 StrucureHasAssetMaintenances
 UtilityVaultHasAssetMaintenances
 IrrigationWireHasAssetMaintenances
 PavementMarkingLineHasAssetMaintenances
 GasPointHasAssetMaintenances
 SewerPointHasProductInformation
 VisitorSignHasProductInformation
 TrafficSignHasProductInformation
 IrrigationPointHasProductInformation
 ElectricPointHasProductInformation
 WaterLineHasAssetMaintenances
 BollardHasAssetMaintenances
 TelecommunicationPointHasProductInformation
 PlantCenterHasPlantCenterAnnotations
 UnpavedSurfaceHasDedications
 TelecommunicationPointHasAssetMaintenances
 GasLineHasAssetMaintenances
 BollardHasProductInformation
 BarrierHasAssetMaintenances
 PoleHasProductInformation
 WaterPointHasProductInformation
 FurnitureHasDedication
 VisitorSignHasAssetMaintenances
 FurnitureHasAssetMaintenances
 UtilityBoxHasAssetMaintenances
 CurbHasAssetMaintenances
 EnclosureHasBarriers
 StormWaterPointHasAssetMaintenances
 WaterReservoirHasAssetMaintenances
 PlantCenterHasPlantLabels
 IrrigationPointHasAssetMaintenances
 SewerPointHasAssetMaintenances
 StormWaterPointHasProductInformation
 TrafficCalmingHasAssetMaintenances
 PlantCenterHasTreeHazardHealths
 ExhibitHasEnclosures
 PavementSegmentHasDedications
 AreaOfInterestHasInstitutions
 WaterReservoirHasProductInformation
 IrrigationControllerHasProductInformation
 SewerLineHasAssetMaintenances
 HydrographicPointHasWaterSamples
 ElectricLineHasAssetMaintenances
 PlantCenterHasDedication
 ElectricPointHasAssetMaintenances
 PlantCenterHasTreeBenefits
 UtilityBoxHasProductInformation
 TrafficCalmingHasProductInformation
 BarrierHasDedications
 GasPointHasProductInformation
 IrrigationHeadHasAssetMaintenances
 WasteContainerHasProductInformation
 IrrigationControllerHasAssetMaintenances
 WasteContainerHasAssetMaintenances
 PlantCenterHasPlantMaintenances
 PoleHasAssetMaintenances
 PavementMarkingPointHasAssetMaintenances
 FurnitureHasProductInformation
 MassPlantingHasPlantCenters

Processing schemas ...
 FeatureDatasets
 FeatureClasses
 Tables

Closing sql files ...

PostGIS Info:
 Name: pagimdb
 Host: localhost
 Port: 5432
 User: postgres
 Password: jama135

Connect to database ...

Updating database views ...

Creating schemas ...

Loading database tables ...
0...10...20...30...40...50...60...70...80...90...100 - done.

Applying sql scripts ...
Traceback (most recent call last):
  File "c:\python27\arcgis10.3\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\arcgis10.3\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\ArcGIS10.3\Scripts\fgdb2postgis.exe\__main__.py", line 9, in <module>
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\__main__.py", line 63, in main
    postgis.apply_sql(filegdb)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 95, in apply_sql
    self.execute_sql(sql_file)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 104, in execute_sql
    cursor.execute(code)
psycopg2.ProgrammingError: column "GLOBALID" of relation "IrrigationLine" does not exist
LINE 2: INSERT INTO "IrrigationLine" ("GLOBALID")
G:\landscape_gis\ParksAndGardensInformationModel2.0.0\converttopostgis_3>

**Comment by gmioannou** [comment]
Please use the latest version 0.2.7 
- yml file will be created automatically at the first run. 
- you can modify it afterwords
- for usage: fgdb2postgis -h 
- documentation not updated yet
thanks

**Comment by sindile** [comment]
The new fgdb2postgis 0.27 worked with no errors. Thanks

**Comment by gmioannou** [comment]
Hi Sindile,
I am very happy to inform you that the tool has been migrated

Please try the latest version (0.3.6) from Pypi
Compatible with python 3.6.9 and ArcGIS Pro 2.5.1

**Comment by sindile** [comment]
Hi Georgios,
I have installed ArcGIS Pro 2.5.1 licensed using a named user, but I get the following error:
Running fgdb2postgis results in The FlexNet Licensing Service is not installed on this machine.

Is the Licensing Manager a requirement when using a named user with ArcGIS Pro?

These are the steps I followed:

I have activated my virtual environment
arcgispro-py3            C:\Users\sindile\AppData\Local\Programs\ArcGIS\Pro\bin\Python\envs\arcgispro-py3
arcgispro-py3-clone   *  C:\Users\sindile\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone
root                     C:\Users\sindile\AppData\Local\Programs\ArcGIS\Pro\bin\Python

I then followed these instructions
        pip install numpy>=1.12.0
        pip install psycopg2>=2.6.2
        pip install ruamel.yaml>=0.15.35
        pip install awesome-slugify==1.6.5

Install fgdb2postgis::
        pip install fgdb2postgis

**Comment by sindile** [comment]
Got it to work - reinstalled license server, thanks.
