### ISSUE TITLE
Missing subtype tables

### ISSUE THREAD

**Issue by sindile** [cartologic/fgdb2postgis#2]
I am not sure what could be the problem, but what I have observed is that not all the subtypes are created, only the two listed below:
Processing subtypes ...
AsssetMaintenance_MAINTENANCERECORDTYPE_lut
PlantMaintenance_MAINTENANCERECORDTYPE_lut

Do I perhaps need to make changes to the yml file, here is its output
Schemas:
- Basemap
- Boundary
- Electric
- Gas
- Hydrography
- Irrigation
- Pedology
- Sewer
- StormWater
- Telecommunication
- Topography
- Vegetation
- VisitorAmenity
- Water
FeatureDatasets:
  Irrigation:
  - Irrigation
  Topography:
  - Topography
  Hydrography:
  - Hydrography
  Electric:
  - Electric
  Gas:
  - Gas
  VisitorAmenity:
  - VisitorAmenity
  Water:
  - Water
  Pedology:
  - Pedology
  Sewer:
  - Sewer
  StormWater:
  - StormWater
  Boundary:
  - Boundary
  Basemap:
  - Basemap
  Vegetation:
  - Vegetation
  Telecommunication:
  - Telecommunication
FeatureClasses:
  public: []
Tables:
  public:
  - AsssetMaintenance
  - Dedication
  - Enclosure
  - Institution
  - PlantAccession
  - PlantLabel
  - PlantMaintenance
  - ProductInformation
  - TreeBenefit
  - TreeHazardHealth
  - WaterSample

**Comment by gmioannou** [comment]
Fixed in 53a7246b4439396a6fd6085943c1982ead3e684a
