### ISSUE TITLE
Unable to write feature

### ISSUE THREAD

**Issue by sindile** [cartologic/fgdb2postgis#4]
I am running the latest version of the script.

The data is from http://solutions.arcgis.com/parks-gardens/facilities/

When trying to run the script with a geodatabase that has records I get the error below
Connect to database ...

Updating database views ...

Creating schemas ...

Loading database tables ...
0...10.Warning 1: Geometry to be inserted is of type Multi Curve, whereas the layer geometry type is Multi Line String.
Insertion is likely to fail
.ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: CREATE TABLE "public"."IrHead" ( "id" SERIAL, PRIMARY KEY ("id"), "GlobalID" VARCHAR NOT NULL, "IrrigationHeadID" INTEGER, "IrrigationHeadType" SMALLINT DEFAULT 6, "HeadModel" VARCHAR(50), "NozzleModel" VARCHAR(50), "Pattern" VARCHAR(
20), "Spread" REAL, "ArcDegree" SMALLINT, "Status" VARCHAR(20) DEFAULT 'Existing', "Condition" VARCHAR(20) DEFAULT 'UNKNOWN', "StationNumber" SMALLINT, "InstallDate" timestamp with time zone, "SurveyDate" timestamp with time zone, "SurveyUserN
ame" VARCHAR(50), "UpdateDate" timestamp with time zone, "UpdateUserName" VARCHAR(50), "IrrigationLineID" INTEGER, "Comments" VARCHAR(100), "geom" geometry(POINT,1) )
ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: Unable to write feature 1 from layer IrHead.
ERROR 1: Terminating translation prematurely after failed
translation of layer IrHead (use -skipfailures to skip errors)

Applying sql scripts ...
Traceback (most recent call last):
  File "c:\python27\arcgis10.3\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\arcgis10.3\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\ArcGIS10.3\Scripts\fgdb2postgis.exe\__main__.py", line 9, in <module>
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\__main__.py", line 83, in main
    postgis.apply_sql(filegdb)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 99, in apply_sql
    self.execute_sql(sql_file)
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis\postgis.py", line 108, in execute_sql
    cursor.execute(code)
psycopg2.ProgrammingError: relation "SurveyMethod_lut" does not exist

**Comment by sindile** [comment]
attached is the xml file.
[IRRIGATIONMAPPER.zip](https://github.com/cartologic/fgdb2postgis/files/1828998/IRRIGATIONMAPPER.zip)

**Comment by gmioannou** [comment]
Please try the latest version (0.3.6) from Pypi
Compatible with python 3.6.9 and ArcGIS Pro 2.5.1

**Comment by sindile** [comment]
Thank you for the update, 
I am using fgdb2postgis -v Version: 0.4
I ran into this error:

Begin Program....
***********************************
Namespace(a_srs='EPSG:2226', database='irrigationmapperdb', fgdb='irrigationmapper.gdb', host='localhost', include_empty=True, lookup_tables_schema='lookup_tables', password='mypassword', port=5432, t_srs='EPSG:2226', user='postgres', version=False, yml=False)
Begin Program....
FileGDB Info:
 Workspace:
 Sqlfolder:
 Yamlfile:
Setting arcpy environment ...
PostGIS Info:
 Database: irrigationmapperdb (EPSG:2226)
 Host: localhost
 Port: 5432
 User: postgres
 Password: mypassword
create_database ...
init...
get_feature_datasets
[u'Irrigation']
get_feature_classes
[{'count': 0, 'feature_type': u'Simple', 'shapeType': u'Point', 'feature': u'IrController', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Point', 'feature': u'IrHead', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Polyline', 'feature': u'IrLine', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Point', 'feature': u'IrPoint', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Polygon', 'feature': u'IrStation', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Point', 'feature': u'IrValveBox', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}, {'count': 0, 'feature_type': u'Simple', 'shapeType': u'Polyline', 'feature': u'IrWire', 'dataset': u'Irrigation', 'foreign_keys': [], 'type': 'feature_class'}]
get_tables
string indices must be integers
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis-0.4-py2.7.egg\fgdb2postgis\filegdb.py", line 85, in process
    self.init()

connect to database ...
Connect to database ...
Updating database views ...
Creating schemas ...
 Unable to locate sql file:
C:\Users\sindile\Documents\esri-data-models\irrigation-mapper\irrigationmapper.gdb.sql\create_schemas.sql
Loading database tables ...
****************************************************************************************************************
FileGDB instance has no attribute 'domain_tables'
  File "c:\python27\arcgis10.3\lib\site-packages\fgdb2postgis-0.4-py2.7.egg\fgdb2postgis\__main__.py", line 82, in main
    postgis.process(filegdb)

****************************************************************************************************************
***********************************
End Program....

**Comment by gmioannou** [comment]
You are using Python 2.x...
Python 3.x IS required for this version
Thanks
