### ISSUE TITLE
Support to Python 3 (Arcgis Pro)

### ISSUE THREAD

**Issue by dersteppenwolf** [cartologic/fgdb2postgis#6]
Is it planned some kind of support to Python 3 (Arcgis Pro)?

The current version isn't compatible with the python 3 version included in arcgis pro: 

```
  File "c:\program files\arcgis\pro\bin\python\envs\arcgispro-py3\lib\site-packages\fgdb2postgis\__main__.py", line 15
    print "Usage:"
                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Usage:")?
```

**Comment by gmioannou** [comment]
Hi Juan,
I am very happy to inform you that the tool has been migrated

Please try the latest version (0.3.5) from Pypi
- Compatible with python 3.6.9 and ArcGIS Pro 2.5.1

**Comment by gmioannou** [comment]
Hi Juan,
I am very happy to inform you that the tool has been migrated

Please try the latest version (0.3.6) from Pypi

Compatible with python 3.6.9 and ArcGIS Pro 2.5.1

**Comment by dersteppenwolf** [comment]
Great!
